AUG:
    RESIZE_METHOD: 'stepscaling' # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: [720, 720] # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    TRAIN_CROP_SIZE: [512, 256]  # crop size for training
    EVAL_CROP_SIZE: [512, 256]  # crop size for evaluating
    CROP_PAD_SIZE: 32
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.5
    RICH_CROP:
        ENABLE: False
        BLUR: True
        BLUR_RATIO: 0.2
        MAX_ROTATION: 15
        MIN_AREA_RATIO: 0.5
        ASPECT_RATIO: 0.5
        BRIGHTNESS_JITTER_RATIO: 0.5
        CONTRAST_JITTER_RATIO: 0.5
        SATURATION_JITTER_RATIO: 0.5
DATASET:
    DATA_DIR: './data/my_train_set/' # 훈련용 데이터셋 경로 default: 'REPO_ROOT_PATH/data/training_data_example/'
    IMAGE_TYPE: 'rgb'  # choice rgb or rgba
    NUM_CLASSES: 2
    TEST_FILE_LIST: './data/my_train_set/test.txt' # 테스트 파일 리스트 텍스트 파일 default: 'REPO_ROOT_PATH/data/training_data_example/test.txt'
    TRAIN_FILE_LIST: './data/my_train_set/train.txt' # 학습 파일 리스트 텍스트 파일 default: 'REPO_ROOT_PATH/data/training_data_example/train.txt'
    VAL_FILE_LIST: './data/my_train_set/val.txt' # 검증 파일 리스트 텍스트 파일 default: 'REPO_ROOT_PATH/data/training_data_example/val.txt'
    IGNORE_INDEX: 255
    PADDING_VALUE: [127.5, 127.5, 127.5]
    MEAN_VALUE: [0.5, 0.5, 0.5]
    STD_VALUE: [0.5, 0.5, 0.5]
    CPU_MULTI_PROCESS_NUMS: 8
FREEZE:
    MODEL_FILENAME: 'model'
    PARAMS_FILENAME: 'params'
MODEL:
    MODEL_NAME: 'lanenet' # 학습 시 모델이름 결정
    FRONT_END: 'bisenetv2' # 학습 시 모델이름 결정
    EMBEDDING_FEATS_DIMS: 4 # 최대 차선 수 
    BISENETV2:
        GE_EXPAND_RATIO: 6 
        SEMANTIC_CHANNEL_LAMBDA: 0.25 
        SEGHEAD_CHANNEL_EXPAND_RATIO: 2
TEST:
    TEST_MODEL: 'model/cityscapes/final'
TRAIN:
    MODEL_SAVE_DIR: 'model/my_train_set/tusimple/' # 모델 저장경로 dafault: 'model/tusimple/'
    TBOARD_SAVE_DIR: 'model/my_train_set/tusimple/tboard/' # 텐서보드 파일 저장 경로 dafault: 'tboard/tusimple/'
    MODEL_PARAMS_CONFIG_FILE_NAME: "model_train_config.json"
    RESTORE_FROM_SNAPSHOT: # 스냅샷으로부터 불러오기
        ENABLE: True # 사용여부 default: False
        SNAPSHOT_PATH: 'model/tusimple_lanenet/tusimple_lanenet.ckpt' # 스냅샷 경로
    SNAPSHOT_EPOCH: 8
    BATCH_SIZE: 4 # default: 32
    VAL_BATCH_SIZE: 4
    EPOCH_NUMS: 905
    WARM_UP: # 저장된 모델 워밍업 설정
        ENABLE: True # 지연 초기화가 요청 지연 시간에 미치는 영향을 줄이기 위해 저장된 모델과 함께 추론 요청 샘플 세트를 제공하여 모델로드시 하위 시스템 및 구성 요소의 초기화를 트리거
        EPOCH_NUMS: 8 # 예열 횟수 설정
    FREEZE_BN: # Freeze Batch Normalization 설정
        ENABLE: False
    COMPUTE_MIOU: # 성능 측정위한 MIOU설정
        ENABLE: True # 사용여부 # default: True
        EPOCH: 1 # 반복 횟수
    MULTI_GPU: # 다중 GPU여부
        ENABLE: False # default: True
        GPU_DEVICES: ['0', '1']
        CHIEF_DEVICE_INDEX: 0
SOLVER:
    LR: 0.001 # 학습률
    LR_POLICY: 'poly' # 학습정책
    LR_POLYNOMIAL_POWER: 0.9
    OPTIMIZER: 'sgd'
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    MOVING_AVE_DECAY: 0.9995
    LOSS_TYPE: 'cross_entropy'
    OHEM:
        ENABLE: False
        SCORE_THRESH: 0.65
        MIN_SAMPLE_NUMS: 65536
GPU:
    GPU_MEMORY_FRACTION: 0.1
    TF_ALLOW_GROWTH: True
POSTPROCESS:
    MIN_AREA_THRESHOLD: 100
    DBSCAN_EPS: 0.35
    DBSCAN_MIN_SAMPLES: 1000
LOG:
    SAVE_DIR: './log'
    LEVEL: INFO
